spring:
  application:
    name: Get light Novel
  client:
    id: "test"
    #test2
    secret: "$2a$10$1OindcsE8qZXrwndTBPM4.QMNxqy0bHzHaEAvBmBosdjCDqwr0MTC"
  datasource:
    url: jdbc:mariadb://localhost:3300/LN
    username: ligth
    password: pwd123
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.mariadb.jdbc.Driver

server:
  port: 9665

cron.task:
  dofus:  0 0/10 * * * ?
logging:
  level:
    ROOT: INFO
