version: '3.4'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    ports:
     - '3300:3306'
    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=LN
      - MARIADB_ROOT_USER=ligth
      - MARIADB_ROOT_PASSWORD=pwd123
    volumes:
      - 'mariadb_data:/bitnami'
#  dofus-api:
#    build:
#      context: .
#    container_name: dofus-api
#    ports:
#      - 9665:9665
#      - 8189:8000
#    command: "java -jar
#               -Djava.security.egd=file:/dev/./urandom \
#               -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000 -Dserver.port=9665 \
#               -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap \
#               /app/dofus-api.jar"
volumes:
  mariadb_data:
    driver: local

